### ISSUE TITLE
VPN Support - OpenVPN

### ISSUE THREAD

**Issue by wjbeckett** [diameter/rtorrent-rutorrent#21]
I'd love the ability to have OpenVPN supported to push all torrent traffic over the VPN but still leaving port 80 accessible locally for the web ui.

Is this possible?

**Comment by Vagabon666** [comment]
Hello,

I am looking for the same improvement, is ther any chance it comes ?

Thank you

**Comment by diameter** [comment]
Hello @Vagabon666 
I do not use vpn and don't have any vpn accounts, so I can't implement and debug this improvement.
And, I think that vpn connection should be established on the docker host, then you'll just need to bind your container to established vpn network interface (https://docs.docker.com/engine/userguide/networking/default_network/binding/)
Though I may be wrong, didn't do any research on this.

**Comment by Vagabon666** [comment]
Hi,
Sorry for the late reply, I was away.

Does it help if I told you that this container is working like a charm, except it is not rutorrent :-) :
haugene/transmission-openvpn

Thank you.

**Comment by leviwheatcroft** [comment]
2 years late to this party...

The best way to do this is to install a docker container running a vpn client, and then add this container to your vpn container's network stack.

There's a few around but the one I've been playing around with is [dperson/vpn-client](https://github.com/dperson/openvpn-client). The readme on that repo explains how to do this.

I don't yet have a working configuration... if you're reading this and interested just ask, by that time I might have it sorted out!

**Comment by Vagabon666** [comment]
Hello,

Thank you for your reply, I am still interested.
I already tried this container but wasn't able to use it on synology.
If you found the way to do it that would be great !!!

See you,
Vagabon.

**Comment by leviwheatcroft** [comment]
It's working now, using docker-compose.

Basically, you create two containers, one from this repo to run rutorrent, and then one to run a vpn client. Then configure the rutorrent container with `network_mode: service:vpn-client` which adds rutorrent container to vpn container's network stack, as though they're behind the same physical adapter.


you make a docker-compose.yml like:

```
version: '3'

services:
  vpn-client:
    image: dperson/openvpn-client
    cap_add:
      - net_admin
    environment:
      - TZ=${TZ}
    volumes:
      - /dev/net:/dev/net:z
      - /srv/config/vpn-client:/vpn
    read_only: false
    tmpfs:
      - /tmp
    restart: unless-stopped
    security_opt:
      - label:disable
    stdin_open: true
    tty: true

    command: -d
  rutorrent:
    image: diameter/rtorrent-rutorrent
    cap_add:
      - net_admin
    depends_on:
      - vpn-client
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    network_mode: service:vpn-client
    volumes:
      - /srv/config/rutorrent:/config
      - /srv/rutorrent:/downloads
      - /srv/complete:/complete

```

and a .env like (`id <user>` to get uid & gid):

```
PUID=999
PGID=999
TZ=Australia/Perth
```

 - Then you get an ovpn config and copy it to `/srv/config/vpn-client/vpn.ovpn` (using the paths I've mapped).
 - `docker ps` to see container names
 - `docker exec -it <rutorrent container> curl ipinfo.io/ip` and it should show you the vpn end point.

This works great... except of course that rutorrent won't be connectable behind a vpn, so now I'm trying to figure out how to "proxify" rutorrent...
