### ISSUE TITLE
can't browse file system in rutorrent ui

### ISSUE THREAD

**Issue by checktravis** [diameter/rtorrent-rutorrent#47]
This is my docker composition:
```
  rutorrent:
    restart: unless-stopped
    container_name: rtorrent-rutorrent
    image: diameter/rtorrent-rutorrent:latest
    ports:
      - "8080:80"
      - "51121:51121/udp"
      - "65012:65012"
      - "6881:6881/udp"
    volumes:
      - /home/docman/diameter/downloads:/downloads
    environment:
      - USR_ID=1001
      - GRP_ID=1001
      - PHP_MEM=1024M
#      - WEBROOT=/downloads
    tty: true
```

I have tried setting the WEBROOT env but either way when I click on the drop down in autotools to set the finished directory path there is no browseable items.

Usually this is a permission issue or a php path setting that needs to be adjusted in config.php but I don't see that exposed anywhere.

Also, I noticed some of the generated files in rutorrent have different ids than the one I used to override, shouldn't everything be owned by that ID? that may be the issue?

This image is much lighter and less complex than others I have tried, nice work.

additional info:
also seeing this repeated in the logs with random ids
rtorrent-rutorrent | 2018-03-01 07:31:44,019 INFO reaped unknown pid 120
